# define default database user, name, and password for PostgreSQL deployment
auth:
  enablePostgresUser: true
  postgresPassword: "foobar"
  username: "immersion"
  password: "foobar"
  database: "immersion"

nameOverride: "immersion"
standalone: "standalone"

# The postgres helm chart deployment will be using PVC postgres-data-claim
primary:
  persistence:
    enabled: true
    existingClaim: "postgres-immersion-data-claim"

volumePermissions:
  enabled: true
