apiVersion: apps/v1
kind: Deployment
metadata:
  name: reading-contest-api
  labels:
    app: reading-contest-api
spec:
  selector:
    matchLabels:
      app: reading-contest-api
  template:
    metadata:
      labels:
        app: reading-contest-api
    spec:
      containers:
        - name: reading-contest-api
          image: reading-contest-api-image
          ports:
            - containerPort: 4000
          envFrom:
            - configMapRef:
                name: reading-contest-api-configmap
            - secretRef:
                name: tadoku-user.reading-contest-api-db.credentials.postgresql.acid.zalan.do
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: tadoku-user.reading-contest-api-db.credentials.postgresql.acid.zalan.do
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tadoku-user.reading-contest-api-db.credentials.postgresql.acid.zalan.do
                  key: password
            - name: DATABASE_URL
              value: "postgres://$(username):$(password)@reading-contest-api-db/tadoku"
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /ping
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /ping
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: reading-contest-api-db
  labels:
    app: reading-contest-api-db
spec:
  teamId: "tadoku"
  volume:
    size: 1Gi
  numberOfInstances: 1
  users:
    tadoku_user: []
  databases:
    tadoku: tadoku_user
  postgresql:
    version: "13"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: reading-contest-api-configmap
data:
  APP_PORT: "4000"
  APP_ENV: development
  APP_NAME: reading-contest-api
  APP_TIMEZONE: UTC
  CORS_ALLOWED_ORIGINS: https://tadoku.app
  DATABASE_MAX_IDLE_CONNS: "10"
  DATABASE_MAX_OPEN_CONNS: "10"
  JWT_SECRET: "abcdefghijklmnopqrstuvwxyz"
  USER_SESSION_COOKIE_NAME: "session_token"
  ERROR_REPORTER_DSN: ""
---
apiVersion: v1
kind: Service
metadata:
  name: reading-contest-api
  labels:
    app: reading-contest-api
    service: reading-contest-api
spec:
  ports:
    - port: 4000
      name: http
  selector:
    app: reading-contest-api
