apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tadoku
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/strip-path: "true"
spec:
  rules:
  - host: langlog.be
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: frontend-webv2
              port:
                number: 3000
        - path: /api/reading-contest
          pathType: Prefix
          backend:
            service:
              name: reading-contest-api
              port:
                number: 4000
        - path: /api/identity
          pathType: Prefix
          backend:
            service:
              name: identity-api
              port:
                number: 4000
        - path: /api/blog/v2
          pathType: Prefix
          backend:
            service:
              name: blog-api
              port:
                number: 8000
        - path: /api/oathkeeper
          pathType: Prefix
          backend:
            service:
              name: oathkeeper-api
              port:
                number: 4456
        - path: /pgweb
          pathType: Prefix
          backend:
            service:
              name: pgweb
              port:
                number: 8081
        - path: /mail
          pathType: Prefix
          backend:
            service:
              name: mailhog
              port:
                number: 8025
  - host: account.langlog.be
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: frontend-auth
              port:
                number: 3001
        - path: /kratos
          pathType: Prefix
          backend:
            service:
              name: kratos-public
              port:
                number: 80
