# define default database user, name, and password for PostgreSQL deployment
auth:
  enablePostgresUser: true
  postgresPassword: "foobar"
  username: "content"
  password: "foobar"
  database: "content"

nameOverride: "content"
standalone: "standalone"

# The postgres helm chart deployment will be using PVC postgres-data-claim
primary:
  persistence:
    enabled: true
    existingClaim: "postgres-content-data-claim"

volumePermissions:
  enabled: true
