- id: "ory:kratos:public"
  upstream:
    preserve_host: true
    url: "http://kratos"
  match:
    url: "http://langlog.be/api/kratos/<**>"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  authenticators:
    - handler: noop
  authorizer:
    handler: allow
  mutators:
    - handler: noop

- id: "ory:kratos-selfservice-ui-node:anonymous"
  upstream:
    preserve_host: true
    url: "http://auth"
  match:
    url: "http://accounts.langlog.be/<{registration,account-recovery,verification,login,error,**.css,**.js,**.png,**.svg,}>"
    methods:
      - GET
  authenticators:
    - handler: anonymous
  authorizer:
    handler: allow
  mutators:
    - handler: noop

- id: "ory:kratos-selfservice-ui-node:protected"
  upstream:
    preserve_host: true
    url: "http://auth"
  match:
    url: "http://accounts.langlog.be/<{settings}>"
    methods:
      - GET
  authenticators:
    - handler: cookie_session
  authorizer:
    handler: allow
  mutators:
    - handler: id_token
  errors:
    - handler: redirect
      config:
        to: http://account.langlog.be/login
