- id: "ory:kratos:public"
  upstream:
    preserve_host: true
    url: "http://kratos"
  match:
    url: "http://langlog.be/api/kratos/<**>"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  authenticators:
    - handler: noop
  authorizer:
    handler: allow
  mutators:
    - handler: noop
