- id: "tadoku:content:api"
  upstream:
    preserve_host: true
    url: "http://content-api:80"
    strip_path: /api/internal/content/
  match:
    url: "http://langlog.be/api/internal/content/<**>"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  authenticators:
    - handler: cookie_session
    - handler: anonymous
  authorizer:
    handler: allow
  mutators:
    - handler: id_token

- id: "tadoku:immersion:api"
  upstream:
    preserve_host: true
    url: "http://immersion-api:80"
    strip_path: /api/internal/immersion/
  match:
    url: "http://langlog.be/api/internal/immersion/<**>"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  authenticators:
    - handler: cookie_session
    - handler: anonymous
  authorizer:
    handler: allow
  mutators:
    - handler: id_token

- id: "echo"
  upstream:
    preserve_host: true
    url: "http://echo"
    strip_path: /api/internal/echo
  match:
    url: "http://langlog.be/api/internal/echo/<**>"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  authenticators:
    - handler: cookie_session
    - handler: anonymous
  authorizer:
    handler: allow
  mutators:
    - handler: id_token