- id: "tadoku:blog:api"
  upstream:
    preserve_host: true
    url: "http://blog-api:8000"
    strip_path: /api/blog/v2
  match:
    url: "http://langlog.be/api/blog/v2/<**>"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  authenticators:
    - handler: cookie_session
    - handler: anonymous
  authorizer:
    handler: allow
  mutators:
    - handler: id_token

- id: "echo"
  upstream:
    preserve_host: true
    url: "http://echo"
    strip_path: /api/echo
  match:
    url: "http://langlog.be/api/echo/<**>"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  authenticators:
    - handler: cookie_session
    - handler: anonymous
  authorizer:
    handler: allow
  mutators:
    - handler: id_token
