openapi: 3.0.3
info:
  title: immersion-api
  license:
    name: MIT
    url: https://github.com/tadoku/tadoku/blob/main/LICENSE
  version: 1.0.0
externalDocs:
  description: Find out more about Tadoku
  url: https://tadoku.github.io/tadoku/
servers:
  - url: https://tadoku.app/api/immersion/
paths:
  /ping:
    get:
      summary: Checks if service is responsive
      operationId: ping
      tags: [metadata]
      responses:
        '200':
          description: successful operation
          immersion:
            text/plain:
              schema:
                type: string
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: ory_kratos_session