apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-api
  labels:
    app: identity-api
spec:
  selector:
    matchLabels:
      app: identity-api
  template:
    metadata:
      labels:
        app: identity-api
    spec:
      containers:
        - name: identity-api
          image: identity-api-image
          ports:
            - containerPort: 4000
          # TODO: migrate db for identity
          envFrom:
            - configMapRef:
                name: identity-api-configmap
          env:
            - name: DATABASE_URL
              value: "postgres://reading_contest:foobar@postgresql-reading-contest/reading_contest"
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /ping
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /ping
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-api-configmap
data:
  APP_PORT: "4000"
  APP_ENV: development
  APP_NAME: identity-api
  APP_TIMEZONE: UTC
  CORS_ALLOWED_ORIGINS: https://tadoku.app
  DATABASE_MAX_IDLE_CONNS: "10"
  DATABASE_MAX_OPEN_CONNS: "10"
  JWT_SECRET: "abcdefghijklmnopqrstuvwxyz"
  USER_SESSION_LENGTH: "792h"
  USER_SESSION_COOKIE_NAME: "session_token"
  ERROR_REPORTER_DSN: ""
---
apiVersion: v1
kind: Service
metadata:
  name: identity-api
  labels:
    app: identity-api
    service: identity-api
spec:
  ports:
    - port: 4000
      name: http
  selector:
    app: identity-api
