apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-api
  labels:
    app: blog-api
spec:
  selector:
    matchLabels:
      app: blog-api
  template:
    metadata:
      labels:
        app: blog-api
    spec:
      initContainers:
        - name: migrations
          image: blog-api-migrate-image
          command: ['/migrate']
          args: ['-source', 'file:///migrations', '-database', '$(DATABASE_URL)', 'up']
          env:
          - name: DATABASE_URL
            value: "postgres://blog:foobar@postgres-blog/blog?sslmode=disable"
      containers:
      - name: blog-api
        image: blog-api-image
        ports:
        - containerPort: 8000
        env:
          - name: API_POSTGRES_URL
            value: "postgres://blog:foobar@postgres-blog/blog?sslmode=disable"
          - name: API_PORT
            value: "8000"
          - name: API_JWKS
            value: "http://oathkeeper-api:4456/.well-known/jwks.json"
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /ping
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 3
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /ping
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: blog-api
  labels:
    app: blog-api
    service: blog-api
spec:
  ports:
  - port: 80
    targetPort: 8000
    name: http
  selector:
    app: blog-api
