apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-api
  labels:
    app: blog-api
spec:
  selector:
    matchLabels:
      app: blog-api
  template:
    metadata:
      labels:
        app: blog-api
    spec:
      containers:
      - name: blog-api
        image: blog-api-image
        ports:
        - containerPort: 8080
        env:
          - name: API_POSTGRES_URL
            value: "postgres://blog:foobar@postgresql-blog/blog?sslmode=disable"
          - name: API_PORT
            value: "8080"
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: blog-api
  labels:
    app: blog-api
    service: blog-api
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: blog-api
