apiVersion: apps/v1
kind: Deployment
metadata:
  name: tadoku-contest-api
  labels:
    app: tadoku-contest-api
spec:
  selector:
    matchLabels:
      app: tadoku-contest-api
  template:
    metadata:
      labels:
        app: tadoku-contest-api
    spec:
      containers:
      - name: tadoku-contest-api
        image: tadoku-contest-api-image
        ports:
        - containerPort: 4000
        envFrom:
          - configMapRef:
              name: tadoku-contest-api-configmap
          - secretRef:
              name: tadoku-user.tadoku-contest-api-db.credentials.postgresql.acid.zalan.do
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: tadoku-user.tadoku-contest-api-db.credentials.postgresql.acid.zalan.do
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tadoku-user.tadoku-contest-api-db.credentials.postgresql.acid.zalan.do
              key: password
        - name: DATABASE_URL
          value: "postgres://$(username):$(password)@tadoku-contest-api-db/tadoku"
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /ping
            port: 4000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /ping
            port: 4000
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: tadoku-contest-api-db
  labels:
    app: tadoku-contest-api-db
spec:
  teamId: "tadoku"
  volume:
    size: 1Gi
  numberOfInstances: 1
  users:
    tadoku_user: []
  databases:
    tadoku: tadoku_user
  postgresql:
    version: "13"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tadoku-contest-api-configmap
data:
  APP_PORT: "4000"
  APP_ENV: development
  APP_NAME: tadoku-contest-api
  APP_TIMEZONE: UTC
  CORS_ALLOWED_ORIGINS: https://tadoku.app
  DATABASE_MAX_IDLE_CONNS: "10"
  DATABASE_MAX_OPEN_CONNS: "10"
  JWT_SECRET: "abcdefghijklmnopqrstuvwxyz"
  USER_SESSION_LENGTH: "792h"
  USER_SESSION_COOKIE_NAME: "session_token"
  ERROR_REPORTER_DSN: ""
  USER_SESSION_API_ENABLED: "false"

