apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgweb
  labels:
    app: pgweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgweb
  template:
    metadata:
      labels:
        app: pgweb
    spec:
      containers:
        - name: pgweb
          image: sosedoff/pgweb
          ports:
            - containerPort: 8081
          envFrom:
            - secretRef:
                name: postgres.tadoku-reading-contest-api-db.credentials.postgresql.acid.zalan.do
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres.tadoku-reading-contest-api-db.credentials.postgresql.acid.zalan.do
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres.tadoku-reading-contest-api-db.credentials.postgresql.acid.zalan.do
                  key: password
            - name: DATABASE_URL
              value: "postgres://$(username):$(password)@tadoku-reading-contest-api-db/tadoku"

---
apiVersion: v1
kind: Service
metadata:
  name: pgweb
  labels:
    app: pgweb
spec:
  ports:
    - port: 8081
      name: http
  selector:
    app: pgweb
