# define default database user, name, and password for PostgreSQL deployment
auth:
  enablePostgresUser: true
  postgresPassword: "foobar"
  username: "kratos"
  password: "foobar"
  database: "kratos"

nameOverride: "kratos"
standalone: "standalone"

# The postgres helm chart deployment will be using PVC postgres-data-claim
primary:
  persistence:
    enabled: true
    existingClaim: "postgres-kratos-data-claim"

volumePermissions:
  enabled: true
